version: '1.0'
stages:
 - prepare
 - build
 - test
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'stridespace/cf-example-python-django'
    revision: master
    git: github
  test_my_image:
     title: Running unit tests
     stage: test
     image: python:buster
     commands:
       - pip install pytest
       - pytest composeexample/utils.py --junitxml="testresults.xml"
  testspace:
    title: Upload to testspace
    stage: test
    image: buildpack-deps:18.04-scm
    commands:
      - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C /usr/local/bin
      - testspace config url open.stridespace.com
      - curl -H "Authorization: $CF_API_KEY" "$CF_URL/api/builds/$CF_BUILD_ID?noAccount=$CF_ACCOUNT"
      - testspace testresults.xml
