version: '1.0'
stages:
 - prepare
 - build
 - test
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'stridespace/cf-example-python-django'
    revision: master
    git: github
  test_my_image:
     title: Running unit tests
     stage: test
     commands:
       - python -m unittest composeexample.utils